import Foundation

enum FoodDatabase {
    static let allFoods: [FoodItem] = proteins + dairy + grains + fruits + vegetables + fatsAndOils + beverages + snackFoods + preparedFoods

    static let proteins: [FoodItem] = [
        FoodItem(name: "Chicken Breast", brand: "Generic", servingSize: "4 oz", servingGrams: 113, calories: 165, protein: 31, carbs: 0, fat: 3.6, category: .protein),
        FoodItem(name: "Ground Beef 90/10", brand: "Generic", servingSize: "4 oz", servingGrams: 113, calories: 200, protein: 22, carbs: 0, fat: 11, category: .protein),
        FoodItem(name: "Salmon Fillet", brand: "Generic", servingSize: "4 oz", servingGrams: 113, calories: 234, protein: 25, carbs: 0, fat: 14, category: .protein),
        FoodItem(name: "Tuna (canned in water)", brand: "StarKist", servingSize: "1 can", servingGrams: 142, calories: 150, protein: 33, carbs: 0, fat: 1, category: .protein),
        FoodItem(name: "Turkey Breast (deli)", brand: "Generic", servingSize: "3 slices", servingGrams: 84, calories: 90, protein: 18, carbs: 1, fat: 1, category: .protein),
        FoodItem(name: "Ground Turkey 93/7", brand: "Generic", servingSize: "4 oz", servingGrams: 113, calories: 170, protein: 21, carbs: 0, fat: 9, category: .protein),
        FoodItem(name: "Shrimp", brand: "Generic", servingSize: "4 oz", servingGrams: 113, calories: 120, protein: 23, carbs: 1, fat: 2, category: .protein),
        FoodItem(name: "Tilapia Fillet", brand: "Generic", servingSize: "4 oz", servingGrams: 113, calories: 110, protein: 23, carbs: 0, fat: 2, category: .protein),
        FoodItem(name: "Pork Tenderloin", brand: "Generic", servingSize: "4 oz", servingGrams: 113, calories: 165, protein: 26, carbs: 0, fat: 6, category: .protein),
        FoodItem(name: "Steak (sirloin)", brand: "Generic", servingSize: "6 oz", servingGrams: 170, calories: 310, protein: 42, carbs: 0, fat: 14, category: .protein),
        FoodItem(name: "Chicken Thigh", brand: "Generic", servingSize: "4 oz", servingGrams: 113, calories: 210, protein: 26, carbs: 0, fat: 11, category: .protein),
        FoodItem(name: "Cod Fillet", brand: "Generic", servingSize: "4 oz", servingGrams: 113, calories: 93, protein: 20, carbs: 0, fat: 1, category: .protein),
        FoodItem(name: "Tofu (firm)", brand: "Generic", servingSize: "1/2 block", servingGrams: 126, calories: 108, protein: 13, carbs: 3, fat: 6, category: .protein),
        FoodItem(name: "Tempeh", brand: "Generic", servingSize: "3 oz", servingGrams: 85, calories: 160, protein: 15, carbs: 9, fat: 9, category: .protein),
        FoodItem(name: "Bison (ground)", brand: "Generic", servingSize: "4 oz", servingGrams: 113, calories: 190, protein: 24, carbs: 0, fat: 10, category: .protein),
        FoodItem(name: "Lamb Chop", brand: "Generic", servingSize: "4 oz", servingGrams: 113, calories: 250, protein: 21, carbs: 0, fat: 18, category: .protein),
        FoodItem(name: "Egg (whole)", brand: "Generic", servingSize: "1 large", servingGrams: 50, calories: 72, protein: 6, carbs: 0.4, fat: 5, category: .protein),
        FoodItem(name: "Egg Whites", brand: "Generic", servingSize: "3 large", servingGrams: 99, calories: 51, protein: 11, carbs: 0.7, fat: 0.2, category: .protein),
        FoodItem(name: "Protein Powder (Whey)", brand: "Optimum Nutrition", servingSize: "1 scoop", servingGrams: 31, calories: 120, protein: 24, carbs: 3, fat: 1.5, category: .protein),
        FoodItem(name: "Protein Bar", brand: "Quest", servingSize: "1 bar", servingGrams: 60, calories: 190, protein: 21, carbs: 21, fat: 7, category: .protein),
        FoodItem(name: "Beef Jerky", brand: "Jack Link's", servingSize: "1 oz", servingGrams: 28, calories: 80, protein: 15, carbs: 3, fat: 1, category: .protein),
        FoodItem(name: "Sardines (canned)", brand: "Generic", servingSize: "1 can", servingGrams: 92, calories: 190, protein: 23, carbs: 0, fat: 11, category: .protein),
        FoodItem(name: "Turkey Meatballs", brand: "Generic", servingSize: "4 meatballs", servingGrams: 112, calories: 200, protein: 22, carbs: 5, fat: 10, category: .protein),
        FoodItem(name: "Edamame", brand: "Generic", servingSize: "1 cup", servingGrams: 155, calories: 190, protein: 17, carbs: 15, fat: 8, category: .protein),
    ]

    static let dairy: [FoodItem] = [
        FoodItem(name: "Greek Yogurt (plain, nonfat)", brand: "Fage", servingSize: "1 cup", servingGrams: 227, calories: 130, protein: 23, carbs: 8, fat: 0, category: .dairy),
        FoodItem(name: "Greek Yogurt (vanilla)", brand: "Chobani", servingSize: "1 cup", servingGrams: 227, calories: 180, protein: 18, carbs: 22, fat: 3, category: .dairy),
        FoodItem(name: "Whole Milk", brand: "Generic", servingSize: "1 cup", servingGrams: 244, calories: 149, protein: 8, carbs: 12, fat: 8, category: .dairy),
        FoodItem(name: "Skim Milk", brand: "Generic", servingSize: "1 cup", servingGrams: 244, calories: 83, protein: 8, carbs: 12, fat: 0.2, category: .dairy),
        FoodItem(name: "Cottage Cheese (low-fat)", brand: "Daisy", servingSize: "1/2 cup", servingGrams: 113, calories: 90, protein: 12, carbs: 5, fat: 2.5, category: .dairy),
        FoodItem(name: "Cheddar Cheese", brand: "Generic", servingSize: "1 oz", servingGrams: 28, calories: 113, protein: 7, carbs: 0.4, fat: 9, category: .dairy),
        FoodItem(name: "Mozzarella (part-skim)", brand: "Generic", servingSize: "1 oz", servingGrams: 28, calories: 72, protein: 7, carbs: 1, fat: 4.5, category: .dairy),
        FoodItem(name: "String Cheese", brand: "Sargento", servingSize: "1 stick", servingGrams: 28, calories: 80, protein: 6, carbs: 1, fat: 6, category: .dairy),
        FoodItem(name: "Cream Cheese", brand: "Philadelphia", servingSize: "2 tbsp", servingGrams: 30, calories: 100, protein: 2, carbs: 1, fat: 9, category: .dairy),
        FoodItem(name: "Parmesan Cheese", brand: "Generic", servingSize: "2 tbsp", servingGrams: 14, calories: 55, protein: 4, carbs: 0.5, fat: 4, category: .dairy),
        FoodItem(name: "Whey Protein Shake", brand: "Fairlife", servingSize: "1 bottle", servingGrams: 340, calories: 150, protein: 30, carbs: 3, fat: 2.5, category: .dairy),
        FoodItem(name: "Chocolate Milk", brand: "Generic", servingSize: "1 cup", servingGrams: 250, calories: 208, protein: 8, carbs: 26, fat: 8, category: .dairy),
        FoodItem(name: "Kefir (plain)", brand: "Lifeway", servingSize: "1 cup", servingGrams: 240, calories: 104, protein: 11, carbs: 12, fat: 2, category: .dairy),
    ]

    static let grains: [FoodItem] = [
        FoodItem(name: "White Rice (cooked)", brand: "Generic", servingSize: "1 cup", servingGrams: 186, calories: 206, protein: 4.3, carbs: 45, fat: 0.4, category: .grains),
        FoodItem(name: "Brown Rice (cooked)", brand: "Generic", servingSize: "1 cup", servingGrams: 195, calories: 216, protein: 5, carbs: 45, fat: 1.8, category: .grains),
        FoodItem(name: "Oatmeal (dry)", brand: "Quaker", servingSize: "1/2 cup", servingGrams: 40, calories: 150, protein: 5, carbs: 27, fat: 3, category: .grains),
        FoodItem(name: "Whole Wheat Bread", brand: "Dave's Killer", servingSize: "1 slice", servingGrams: 45, calories: 110, protein: 5, carbs: 22, fat: 1.5, category: .grains),
        FoodItem(name: "White Bread", brand: "Generic", servingSize: "1 slice", servingGrams: 30, calories: 79, protein: 3, carbs: 15, fat: 1, category: .grains),
        FoodItem(name: "Pasta (cooked)", brand: "Generic", servingSize: "1 cup", servingGrams: 140, calories: 220, protein: 8, carbs: 43, fat: 1.3, category: .grains),
        FoodItem(name: "Quinoa (cooked)", brand: "Generic", servingSize: "1 cup", servingGrams: 185, calories: 222, protein: 8, carbs: 39, fat: 3.5, category: .grains),
        FoodItem(name: "Tortilla (flour, 8\")", brand: "Mission", servingSize: "1 tortilla", servingGrams: 49, calories: 140, protein: 4, carbs: 24, fat: 3.5, category: .grains),
        FoodItem(name: "Bagel (plain)", brand: "Thomas", servingSize: "1 bagel", servingGrams: 95, calories: 270, protein: 10, carbs: 53, fat: 1.5, category: .grains),
        FoodItem(name: "English Muffin", brand: "Thomas", servingSize: "1 muffin", servingGrams: 57, calories: 130, protein: 5, carbs: 25, fat: 1, category: .grains),
        FoodItem(name: "Granola", brand: "Generic", servingSize: "1/2 cup", servingGrams: 55, calories: 240, protein: 5, carbs: 34, fat: 10, category: .grains),
        FoodItem(name: "Rice Cakes", brand: "Quaker", servingSize: "2 cakes", servingGrams: 18, calories: 70, protein: 1, carbs: 15, fat: 0.5, category: .grains),
        FoodItem(name: "Couscous (cooked)", brand: "Generic", servingSize: "1 cup", servingGrams: 157, calories: 176, protein: 6, carbs: 36, fat: 0.3, category: .grains),
        FoodItem(name: "Sweet Potato", brand: "Generic", servingSize: "1 medium", servingGrams: 130, calories: 112, protein: 2, carbs: 26, fat: 0.1, category: .grains),
        FoodItem(name: "Potato (baked)", brand: "Generic", servingSize: "1 medium", servingGrams: 173, calories: 161, protein: 4, carbs: 37, fat: 0.2, category: .grains),
        FoodItem(name: "Pancake Mix", brand: "Kodiak", servingSize: "1/2 cup dry", servingGrams: 53, calories: 190, protein: 14, carbs: 30, fat: 2.5, category: .grains),
        FoodItem(name: "Cereal (Cheerios)", brand: "General Mills", servingSize: "1 cup", servingGrams: 28, calories: 100, protein: 3, carbs: 20, fat: 2, category: .grains),
        FoodItem(name: "Overnight Oats", brand: "Generic", servingSize: "1 cup", servingGrams: 220, calories: 310, protein: 12, carbs: 45, fat: 9, category: .grains),
    ]

    static let fruits: [FoodItem] = [
        FoodItem(name: "Banana", brand: "Generic", servingSize: "1 medium", servingGrams: 118, calories: 105, protein: 1.3, carbs: 27, fat: 0.4, category: .fruits),
        FoodItem(name: "Apple", brand: "Generic", servingSize: "1 medium", servingGrams: 182, calories: 95, protein: 0.5, carbs: 25, fat: 0.3, category: .fruits),
        FoodItem(name: "Blueberries", brand: "Generic", servingSize: "1 cup", servingGrams: 148, calories: 84, protein: 1.1, carbs: 21, fat: 0.5, category: .fruits),
        FoodItem(name: "Strawberries", brand: "Generic", servingSize: "1 cup", servingGrams: 152, calories: 49, protein: 1, carbs: 12, fat: 0.5, category: .fruits),
        FoodItem(name: "Orange", brand: "Generic", servingSize: "1 medium", servingGrams: 131, calories: 62, protein: 1.2, carbs: 15, fat: 0.2, category: .fruits),
        FoodItem(name: "Grapes", brand: "Generic", servingSize: "1 cup", servingGrams: 151, calories: 104, protein: 1.1, carbs: 27, fat: 0.2, category: .fruits),
        FoodItem(name: "Avocado", brand: "Generic", servingSize: "1/2 fruit", servingGrams: 68, calories: 114, protein: 1.3, carbs: 6, fat: 10, category: .fruits),
        FoodItem(name: "Mango", brand: "Generic", servingSize: "1 cup sliced", servingGrams: 165, calories: 99, protein: 1.4, carbs: 25, fat: 0.6, category: .fruits),
        FoodItem(name: "Pineapple", brand: "Generic", servingSize: "1 cup chunks", servingGrams: 165, calories: 82, protein: 0.9, carbs: 22, fat: 0.2, category: .fruits),
        FoodItem(name: "Watermelon", brand: "Generic", servingSize: "1 cup diced", servingGrams: 152, calories: 46, protein: 0.9, carbs: 12, fat: 0.2, category: .fruits),
        FoodItem(name: "Dried Cranberries", brand: "Craisins", servingSize: "1/4 cup", servingGrams: 40, calories: 130, protein: 0, carbs: 33, fat: 0, category: .fruits),
        FoodItem(name: "Dates (Medjool)", brand: "Generic", servingSize: "2 dates", servingGrams: 48, calories: 133, protein: 0.9, carbs: 36, fat: 0.1, category: .fruits),
        FoodItem(name: "Mixed Berries (frozen)", brand: "Generic", servingSize: "1 cup", servingGrams: 140, calories: 70, protein: 1, carbs: 17, fat: 0, category: .fruits),
    ]

    static let vegetables: [FoodItem] = [
        FoodItem(name: "Broccoli", brand: "Generic", servingSize: "1 cup", servingGrams: 91, calories: 31, protein: 2.5, carbs: 6, fat: 0.4, category: .vegetables),
        FoodItem(name: "Spinach (raw)", brand: "Generic", servingSize: "2 cups", servingGrams: 60, calories: 14, protein: 1.7, carbs: 2.2, fat: 0.2, category: .vegetables),
        FoodItem(name: "Mixed Salad Greens", brand: "Generic", servingSize: "2 cups", servingGrams: 85, calories: 15, protein: 1.5, carbs: 2.5, fat: 0.2, category: .vegetables),
        FoodItem(name: "Bell Pepper (red)", brand: "Generic", servingSize: "1 medium", servingGrams: 119, calories: 37, protein: 1.2, carbs: 7, fat: 0.4, category: .vegetables),
        FoodItem(name: "Carrots", brand: "Generic", servingSize: "1 cup chopped", servingGrams: 128, calories: 52, protein: 1.2, carbs: 12, fat: 0.3, category: .vegetables),
        FoodItem(name: "Green Beans", brand: "Generic", servingSize: "1 cup", servingGrams: 125, calories: 34, protein: 2, carbs: 7, fat: 0.1, category: .vegetables),
        FoodItem(name: "Asparagus", brand: "Generic", servingSize: "6 spears", servingGrams: 90, calories: 20, protein: 2.2, carbs: 3.7, fat: 0.2, category: .vegetables),
        FoodItem(name: "Cucumber", brand: "Generic", servingSize: "1/2 medium", servingGrams: 150, calories: 22, protein: 1, carbs: 4.5, fat: 0.2, category: .vegetables),
        FoodItem(name: "Tomato", brand: "Generic", servingSize: "1 medium", servingGrams: 123, calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2, category: .vegetables),
        FoodItem(name: "Mushrooms", brand: "Generic", servingSize: "1 cup sliced", servingGrams: 70, calories: 15, protein: 2.2, carbs: 2.3, fat: 0.2, category: .vegetables),
        FoodItem(name: "Zucchini", brand: "Generic", servingSize: "1 medium", servingGrams: 196, calories: 33, protein: 2.4, carbs: 6, fat: 0.6, category: .vegetables),
        FoodItem(name: "Cauliflower", brand: "Generic", servingSize: "1 cup", servingGrams: 107, calories: 27, protein: 2, carbs: 5.3, fat: 0.3, category: .vegetables),
        FoodItem(name: "Brussels Sprouts", brand: "Generic", servingSize: "1 cup", servingGrams: 88, calories: 38, protein: 3, carbs: 8, fat: 0.3, category: .vegetables),
        FoodItem(name: "Kale (raw)", brand: "Generic", servingSize: "2 cups", servingGrams: 40, calories: 15, protein: 1.3, carbs: 2, fat: 0.3, category: .vegetables),
        FoodItem(name: "Onion", brand: "Generic", servingSize: "1/2 medium", servingGrams: 75, calories: 30, protein: 0.8, carbs: 7, fat: 0.1, category: .vegetables),
        FoodItem(name: "Corn (sweet)", brand: "Generic", servingSize: "1 ear", servingGrams: 90, calories: 80, protein: 3, carbs: 17, fat: 1, category: .vegetables),
    ]

    static let fatsAndOils: [FoodItem] = [
        FoodItem(name: "Olive Oil", brand: "Generic", servingSize: "1 tbsp", servingGrams: 14, calories: 119, protein: 0, carbs: 0, fat: 14, category: .fats),
        FoodItem(name: "Butter", brand: "Generic", servingSize: "1 tbsp", servingGrams: 14, calories: 102, protein: 0.1, carbs: 0, fat: 12, category: .fats),
        FoodItem(name: "Coconut Oil", brand: "Generic", servingSize: "1 tbsp", servingGrams: 14, calories: 121, protein: 0, carbs: 0, fat: 14, category: .fats),
        FoodItem(name: "Almonds", brand: "Blue Diamond", servingSize: "1 oz (23 nuts)", servingGrams: 28, calories: 164, protein: 6, carbs: 6, fat: 14, category: .fats),
        FoodItem(name: "Walnuts", brand: "Generic", servingSize: "1 oz", servingGrams: 28, calories: 185, protein: 4.3, carbs: 4, fat: 18, category: .fats),
        FoodItem(name: "Peanut Butter", brand: "Jif", servingSize: "2 tbsp", servingGrams: 32, calories: 190, protein: 7, carbs: 8, fat: 16, category: .fats),
        FoodItem(name: "Almond Butter", brand: "Justin's", servingSize: "2 tbsp", servingGrams: 32, calories: 190, protein: 7, carbs: 6, fat: 17, category: .fats),
        FoodItem(name: "Cashews", brand: "Generic", servingSize: "1 oz", servingGrams: 28, calories: 157, protein: 5, carbs: 9, fat: 12, category: .fats),
        FoodItem(name: "Peanuts", brand: "Planters", servingSize: "1 oz", servingGrams: 28, calories: 170, protein: 7, carbs: 5, fat: 14, category: .fats),
        FoodItem(name: "Chia Seeds", brand: "Generic", servingSize: "2 tbsp", servingGrams: 28, calories: 140, protein: 5, carbs: 12, fat: 9, category: .fats),
        FoodItem(name: "Flax Seeds", brand: "Generic", servingSize: "2 tbsp", servingGrams: 20, calories: 110, protein: 4, carbs: 6, fat: 9, category: .fats),
        FoodItem(name: "Sunflower Seeds", brand: "Generic", servingSize: "1/4 cup", servingGrams: 35, calories: 200, protein: 7, carbs: 7, fat: 17, category: .fats),
        FoodItem(name: "MCT Oil", brand: "Generic", servingSize: "1 tbsp", servingGrams: 14, calories: 130, protein: 0, carbs: 0, fat: 14, category: .fats),
        FoodItem(name: "Guacamole", brand: "Generic", servingSize: "2 tbsp", servingGrams: 30, calories: 50, protein: 0.6, carbs: 3, fat: 4, category: .fats),
        FoodItem(name: "Hummus", brand: "Sabra", servingSize: "2 tbsp", servingGrams: 28, calories: 70, protein: 2, carbs: 4, fat: 5, category: .fats),
        FoodItem(name: "Dark Chocolate (85%)", brand: "Lindt", servingSize: "3 squares", servingGrams: 30, calories: 170, protein: 3, carbs: 10, fat: 14, category: .fats),
    ]

    static let beverages: [FoodItem] = [
        FoodItem(name: "Black Coffee", brand: "Generic", servingSize: "8 oz", servingGrams: 237, calories: 2, protein: 0.3, carbs: 0, fat: 0, category: .beverages),
        FoodItem(name: "Latte (whole milk)", brand: "Starbucks", servingSize: "16 oz", servingGrams: 473, calories: 220, protein: 11, carbs: 18, fat: 11, category: .beverages),
        FoodItem(name: "Oat Milk Latte", brand: "Starbucks", servingSize: "16 oz", servingGrams: 473, calories: 270, protein: 5, carbs: 36, fat: 11, category: .beverages),
        FoodItem(name: "Green Tea", brand: "Generic", servingSize: "8 oz", servingGrams: 237, calories: 2, protein: 0, carbs: 0, fat: 0, category: .beverages),
        FoodItem(name: "Orange Juice", brand: "Tropicana", servingSize: "8 oz", servingGrams: 248, calories: 110, protein: 2, carbs: 26, fat: 0, category: .beverages),
        FoodItem(name: "Coconut Water", brand: "Vita Coco", servingSize: "11 oz", servingGrams: 330, calories: 60, protein: 0, carbs: 15, fat: 0, category: .beverages),
        FoodItem(name: "Almond Milk (unsweetened)", brand: "Almond Breeze", servingSize: "1 cup", servingGrams: 240, calories: 30, protein: 1, carbs: 1, fat: 2.5, category: .beverages),
        FoodItem(name: "Oat Milk", brand: "Oatly", servingSize: "1 cup", servingGrams: 240, calories: 120, protein: 3, carbs: 16, fat: 5, category: .beverages),
        FoodItem(name: "Sports Drink", brand: "Gatorade", servingSize: "20 oz", servingGrams: 591, calories: 140, protein: 0, carbs: 36, fat: 0, category: .beverages),
        FoodItem(name: "Pre-Workout Drink", brand: "C4", servingSize: "1 scoop", servingGrams: 6, calories: 5, protein: 0, carbs: 1, fat: 0, category: .beverages),
        FoodItem(name: "BCAA Drink", brand: "Xtend", servingSize: "1 scoop", servingGrams: 14, calories: 0, protein: 0, carbs: 0, fat: 0, category: .beverages),
        FoodItem(name: "Smoothie (fruit)", brand: "Generic", servingSize: "16 oz", servingGrams: 473, calories: 280, protein: 4, carbs: 62, fat: 2, category: .beverages),
        FoodItem(name: "Protein Smoothie", brand: "Generic", servingSize: "16 oz", servingGrams: 473, calories: 350, protein: 30, carbs: 40, fat: 8, category: .beverages),
        FoodItem(name: "Kombucha", brand: "GT's", servingSize: "8 oz", servingGrams: 240, calories: 30, protein: 0, carbs: 7, fat: 0, category: .beverages),
    ]

    static let snackFoods: [FoodItem] = [
        FoodItem(name: "Apple with Peanut Butter", brand: "Generic", servingSize: "1 apple + 2 tbsp", servingGrams: 214, calories: 285, protein: 7.5, carbs: 33, fat: 16, category: .snacks),
        FoodItem(name: "Protein Ball", brand: "Generic", servingSize: "2 balls", servingGrams: 50, calories: 180, protein: 8, carbs: 20, fat: 8, category: .snacks),
        FoodItem(name: "Trail Mix", brand: "Planters", servingSize: "1/4 cup", servingGrams: 40, calories: 170, protein: 5, carbs: 15, fat: 11, category: .snacks),
        FoodItem(name: "Popcorn (air-popped)", brand: "SkinnyPop", servingSize: "3 cups", servingGrams: 28, calories: 140, protein: 2, carbs: 16, fat: 8, category: .snacks),
        FoodItem(name: "Granola Bar", brand: "KIND", servingSize: "1 bar", servingGrams: 40, calories: 200, protein: 6, carbs: 16, fat: 13, category: .snacks),
        FoodItem(name: "Rice Cake with Almond Butter", brand: "Generic", servingSize: "1 cake + 1 tbsp", servingGrams: 25, calories: 130, protein: 4, carbs: 10, fat: 9, category: .snacks),
        FoodItem(name: "Celery with Peanut Butter", brand: "Generic", servingSize: "3 stalks + 2 tbsp", servingGrams: 120, calories: 200, protein: 7, carbs: 10, fat: 16, category: .snacks),
        FoodItem(name: "Crackers (whole wheat)", brand: "Triscuit", servingSize: "6 crackers", servingGrams: 28, calories: 120, protein: 3, carbs: 20, fat: 4, category: .snacks),
        FoodItem(name: "Tortilla Chips", brand: "Tostitos", servingSize: "1 oz", servingGrams: 28, calories: 140, protein: 2, carbs: 19, fat: 7, category: .snacks),
        FoodItem(name: "Pretzels", brand: "Snyder's", servingSize: "1 oz", servingGrams: 28, calories: 110, protein: 3, carbs: 23, fat: 1, category: .snacks),
        FoodItem(name: "Yogurt Parfait", brand: "Generic", servingSize: "1 cup", servingGrams: 200, calories: 240, protein: 15, carbs: 32, fat: 6, category: .snacks),
        FoodItem(name: "Banana Chips", brand: "Generic", servingSize: "1 oz", servingGrams: 28, calories: 147, protein: 0.6, carbs: 17, fat: 9, category: .snacks),
    ]

    static let preparedFoods: [FoodItem] = [
        FoodItem(name: "Chicken & Rice Bowl", brand: "Generic", servingSize: "1 bowl", servingGrams: 350, calories: 480, protein: 35, carbs: 52, fat: 12, category: .prepared),
        FoodItem(name: "Grilled Chicken Salad", brand: "Generic", servingSize: "1 salad", servingGrams: 300, calories: 350, protein: 32, carbs: 14, fat: 18, category: .prepared),
        FoodItem(name: "Turkey & Cheese Sandwich", brand: "Generic", servingSize: "1 sandwich", servingGrams: 200, calories: 380, protein: 28, carbs: 35, fat: 14, category: .prepared),
        FoodItem(name: "Chicken Burrito Bowl", brand: "Chipotle", servingSize: "1 bowl", servingGrams: 500, calories: 665, protein: 44, carbs: 56, fat: 28, category: .prepared),
        FoodItem(name: "Grilled Salmon Plate", brand: "Generic", servingSize: "1 plate", servingGrams: 350, calories: 520, protein: 38, carbs: 35, fat: 22, category: .prepared),
        FoodItem(name: "Stir-Fry (chicken & veggies)", brand: "Generic", servingSize: "1.5 cups", servingGrams: 300, calories: 320, protein: 28, carbs: 20, fat: 14, category: .prepared),
        FoodItem(name: "Pasta with Meat Sauce", brand: "Generic", servingSize: "1.5 cups", servingGrams: 350, calories: 450, protein: 22, carbs: 55, fat: 14, category: .prepared),
        FoodItem(name: "Sushi Roll (California)", brand: "Generic", servingSize: "8 pieces", servingGrams: 200, calories: 250, protein: 9, carbs: 38, fat: 7, category: .prepared),
        FoodItem(name: "Pizza (cheese, 2 slices)", brand: "Generic", servingSize: "2 slices", servingGrams: 200, calories: 560, protein: 20, carbs: 62, fat: 24, category: .prepared),
        FoodItem(name: "Burger (no bun)", brand: "Generic", servingSize: "1 patty", servingGrams: 170, calories: 310, protein: 32, carbs: 0, fat: 20, category: .prepared),
        FoodItem(name: "Taco (soft, chicken)", brand: "Generic", servingSize: "2 tacos", servingGrams: 200, calories: 380, protein: 24, carbs: 32, fat: 16, category: .prepared),
        FoodItem(name: "Poke Bowl", brand: "Generic", servingSize: "1 bowl", servingGrams: 400, calories: 520, protein: 30, carbs: 55, fat: 18, category: .prepared),
        FoodItem(name: "Overnight Oats (protein)", brand: "Generic", servingSize: "1 jar", servingGrams: 280, calories: 380, protein: 25, carbs: 45, fat: 10, category: .prepared),
        FoodItem(name: "Egg White Omelette", brand: "Generic", servingSize: "1 omelette", servingGrams: 200, calories: 180, protein: 24, carbs: 4, fat: 7, category: .prepared),
        FoodItem(name: "Acai Bowl", brand: "Generic", servingSize: "1 bowl", servingGrams: 350, calories: 400, protein: 8, carbs: 68, fat: 12, category: .prepared),
        FoodItem(name: "Protein Pancakes", brand: "Generic", servingSize: "3 pancakes", servingGrams: 180, calories: 340, protein: 28, carbs: 36, fat: 8, category: .prepared),
        FoodItem(name: "Meal Prep Chicken Bowl", brand: "Generic", servingSize: "1 container", servingGrams: 350, calories: 420, protein: 38, carbs: 40, fat: 12, category: .prepared),
        FoodItem(name: "Greek Salad with Chicken", brand: "Generic", servingSize: "1 salad", servingGrams: 320, calories: 380, protein: 30, carbs: 12, fat: 24, category: .prepared),
        FoodItem(name: "Turkey Lettuce Wraps", brand: "Generic", servingSize: "3 wraps", servingGrams: 200, calories: 280, protein: 26, carbs: 8, fat: 16, category: .prepared),
        FoodItem(name: "Chicken Caesar Wrap", brand: "Generic", servingSize: "1 wrap", servingGrams: 250, calories: 450, protein: 30, carbs: 38, fat: 20, category: .prepared),
        FoodItem(name: "Beef & Broccoli", brand: "Generic", servingSize: "1.5 cups", servingGrams: 300, calories: 380, protein: 30, carbs: 18, fat: 20, category: .prepared),
        FoodItem(name: "Shrimp Stir-Fry", brand: "Generic", servingSize: "1.5 cups", servingGrams: 280, calories: 290, protein: 28, carbs: 22, fat: 10, category: .prepared),
    ]
}
