// User-context injection helper for the ai-proxy edge function.
//
// For a whitelisted set of prompt_ids, calls public.rebuild_user_context
// via the service-role client and returns a formatted block the proxy can
// prepend to the system message so the model sees the user's running
// protocol / metrics / bloodwork / nutrition summaries.
//
// All public functions are best-effort: on any error or missing row,
// fetchUserContextBlock returns null and the caller proceeds with the
// original prompt. Context injection is an enhancement, never a
// precondition.

// Prompt-ids that should have user_context injected. Add cautiously:
// every new entry roughly doubles per-call read traffic on user_context.
// Start with journey_narrative since it benefits most from running
// context and is also the highest-cost surface per call.
export const TEMPLATES_WITH_CONTEXT: Set<string> = new Set([
  "journey_narrative",
]);

export interface UserContextRow {
  user_id: string;
  context_version: number;
  generated_at: string;
  source_event_id: string | null;
  protocol_summary: unknown;
  metrics_summary: unknown;
  bloodwork_summary: unknown;
  nutrition_summary: unknown;
  expires_at: string;
  created_at: string;
  updated_at: string;
}

export interface UserContextBlock {
  block: string;            // text to prepend to the system prompt
  generatedAt: string;      // ISO timestamp from user_context.generated_at
  ageSeconds: number;       // age at fetch time, floored to integer seconds
}

// deno-lint-ignore no-explicit-any
export async function fetchUserContextBlock(admin: any, userId: string): Promise<UserContextBlock | null> {
  try {
    // rebuild_user_context returns SETOF user_context. With supabase-js
    // the RPC returns the row(s) as an array; we read the first.
    const { data, error } = await admin.rpc("rebuild_user_context", {
      p_user_id: userId,
      p_force: false,
    });
    if (error) return null;
    const row: UserContextRow | null = Array.isArray(data)
      ? (data[0] ?? null)
      : (data ?? null);
    if (!row || !row.generated_at) return null;

    const generatedAtMs = Date.parse(row.generated_at);
    if (!Number.isFinite(generatedAtMs)) return null;
    const ageSeconds = Math.max(0, Math.floor((Date.now() - generatedAtMs) / 1000));

    const block = formatContextBlock(row);
    return { block, generatedAt: row.generated_at, ageSeconds };
  } catch (_) {
    return null;
  }
}

// Format the four summary jsonb fields into a single text block the
// model can read. Wrapped in <user_context> tags so prompt authors can
// reference it explicitly. Stable key order keeps Anthropic prompt
// caching effective across calls for the same user.
function formatContextBlock(row: UserContextRow): string {
  const parts: string[] = [
    "<user_context>",
    "This block is generated by the server from the user's logged data.",
    "It is the source of truth for the user's current state. Do not ask",
    "the user to repeat anything that is already captured here.",
    "",
    "<protocol_summary>",
    safeStringify(row.protocol_summary),
    "</protocol_summary>",
    "",
    "<metrics_summary>",
    safeStringify(row.metrics_summary),
    "</metrics_summary>",
    "",
    "<bloodwork_summary>",
    safeStringify(row.bloodwork_summary),
    "</bloodwork_summary>",
    "",
    "<nutrition_summary>",
    safeStringify(row.nutrition_summary),
    "</nutrition_summary>",
    "</user_context>",
  ];
  return parts.join("\n");
}

function safeStringify(v: unknown): string {
  if (v === null || v === undefined) return "{}";
  if (typeof v === "string") return v;
  try { return JSON.stringify(v, null, 2); }
  catch (_) { return "{}"; }
}

// Inject the context block into a chat-completion body as a leading
// system message. If a system message already exists, prepend to it.
// If not, push a new system message at index 0. Returns true if any
// mutation happened. Body is mutated in place.
export function injectContextIntoBody(body: Record<string, unknown>, block: string): boolean {
  const messages = body.messages;
  if (!Array.isArray(messages)) return false;

  // Find the first system message, if any.
  for (const msg of messages) {
    if (!msg || typeof msg !== "object") continue;
    const m = msg as Record<string, unknown>;
    if (m.role !== "system") continue;
    const content = m.content;
    if (typeof content === "string") {
      m.content = block + "\n\n" + content;
      return true;
    }
    if (Array.isArray(content)) {
      // Insert a leading text block so the context comes before existing
      // content. Existing cache_control tags on later blocks stay intact.
      content.unshift({ type: "text", text: block + "\n\n" });
      return true;
    }
    // Unknown shape: fall through and inject a new system message.
    break;
  }

  // No system message present (or unknown shape). Prepend a fresh one.
  messages.unshift({ role: "system", content: block });
  return true;
}
